{"Events":[{"Id":null,"Date":"2019-03-04T16:16:40.8652636+00:00","Type":null,"Description":"Error: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at DigitalEyes.GitHub.RepoSentinel.Function1.Run(TimerInfo myTimer, TraceWriter log)\r\n---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---\r\n","Notes":null,"JsonExtras":null,"Failed":true}]}