{"Events":[{"Id":null,"Date":"2019-08-22T08:55:05.2281467+00:00","Type":null,"Description":"Error: System.AggregateException: One or more errors occurred. ---> Octokit.ApiException: An error occurred with this API request\r\n   at Octokit.Connection.HandleErrors(IResponse response)\r\n   at Octokit.Connection.<RunRequest>d__58.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Octokit.Connection.<Run>d__57`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Octokit.ApiConnection.<Patch>d__31`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Docs.Digest.GitHubActor.RemoteFileManager.<CreateRemoteRepoFilesAsync>d__0.MoveNext() in C:\\Users\\peter\\source\\repos\\Docs.Digest\\Docs.Digest.GitHubActor\\RemoteFileManager.cs:line 51\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DigitalEyes.GitHub.RepoSentinel.Helpers.RepoManager.<SaveSentinelPollStatusAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DigitalEyes.GitHub.RepoSentinel.Helpers.RepoMonitor.<SaveSentinelPollStatusAsync>d__13.MoveNext()\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at DigitalEyes.GitHub.RepoSentinel.Function1.Run(TimerInfo myTimer, TraceWriter log)\r\n---> (Inner Exception #0) Octokit.ApiException: An error occurred with this API request\r\n   at Octokit.Connection.HandleErrors(IResponse response)\r\n   at Octokit.Connection.<RunRequest>d__58.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Octokit.Connection.<Run>d__57`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Octokit.ApiConnection.<Patch>d__31`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Docs.Digest.GitHubActor.RemoteFileManager.<CreateRemoteRepoFilesAsync>d__0.MoveNext() in C:\\Users\\peter\\source\\repos\\Docs.Digest\\Docs.Digest.GitHubActor\\RemoteFileManager.cs:line 51\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DigitalEyes.GitHub.RepoSentinel.Helpers.RepoManager.<SaveSentinelPollStatusAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DigitalEyes.GitHub.RepoSentinel.Helpers.RepoMonitor.<SaveSentinelPollStatusAsync>d__13.MoveNext()\r\n<---\r\n","Notes":null,"JsonExtras":null,"Failed":true}]}